pipeline:
  build:
    image: index.qiniu.com/kci/golang:1.6
    commands:
      - ls -l &&  pwd
      - go build helloworld.go
  index.qiniu.com/kci/plugin_docker:
    repo: wanglei/sample-helloworld
    workdir: ./go
    tag: latest
    kirk_autoupdate: [ wanglei.wanglei2/default/helloworld, wanglei.wangtest/default/helloworld1 ] 
  index.qiniu.com/kci/plugin_kodo:
      bucket: test
      source: .
      target: /
      delete: true
      zone: 0
  index.qiniu.com/kci/plugin_email:
    recipients:
      - 541004974@qq.com
    when:
      event: [push, pull_request, tag, deployment]
      status:  [ failure, success ]
